name: CSE Scraper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Verify files
        run: ls -la  # Debug file locations
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install requests pandas beautifulsoup4 lxml
          
      - name: Run scraper
        run: |
          if [ -f cse_scrape.py ]; then
            python cse_scrape.py
          else
            echo "ERROR: cse_scrape.py not found!"
            echo "Current files:"
            ls -la
            exit 1
          fi
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: cse-data
          path: cse_data.csv
